language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - hhvm
  
matrix:
  include:
    - php: '5.4'
      dist: trusty
    - php: '5.5'
      dist: trusty
  allow_failures:
    - php: hhvm
  fast_finish: true
  
sudo: false

install:
  - travis_retry composer self-update
  - travis_wait composer install --no-interaction --prefer-source --ignore-platform-reqs --dev
  - travis_wait composer update

script: ./vendor/bin/phpunit
